name: "e2e"

on: [ "push" ]

jobs:
    test-e2e:
        name: Run E2E tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Run tests
              run: npm playwright test

            - name: Upload Test Result
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: Test Result
                  path: test-results
